//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle

  let segue = segue()
  let id = id()
  let reuseIdentifier = reuseIdentifier()

  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var nib: nib { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func nib(bundle: Foundation.Bundle) -> nib {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.nib.validate()
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 13 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// Value: DemoApp
      ///
      /// Key: appName
      var appName: RswiftResources.StringResource { .init(key: "appName", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Can't convert data into type
      ///
      /// Key: canNotConverData
      var canNotConverData: RswiftResources.StringResource { .init(key: "canNotConverData", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Server or client error:
      ///
      /// Key: clientOrServerError
      var clientOrServerError: RswiftResources.StringResource { .init(key: "clientOrServerError", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: DELETE
      ///
      /// Key: delete
      var delete: RswiftResources.StringResource { .init(key: "delete", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Download completed
      ///
      /// Key: downloadCompleted
      var downloadCompleted: RswiftResources.StringResource { .init(key: "downloadCompleted", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Empty body
      ///
      /// Key: emptyBody
      var emptyBody: RswiftResources.StringResource { .init(key: "emptyBody", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Error in response body:
      ///
      /// Key: errorInResponseBody
      var errorInResponseBody: RswiftResources.StringResource { .init(key: "errorInResponseBody", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: GET
      ///
      /// Key: get
      var get: RswiftResources.StringResource { .init(key: "get", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: No data found
      ///
      /// Key: noData
      var noData: RswiftResources.StringResource { .init(key: "noData", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: PATCH
      ///
      /// Key: patch
      var patch: RswiftResources.StringResource { .init(key: "patch", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: POST
      ///
      /// Key: post
      var post: RswiftResources.StringResource { .init(key: "post", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: PUT
      ///
      /// Key: put
      var put: RswiftResources.StringResource { .init(key: "put", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Something went wrong while encoding
      ///
      /// Key: somethingWentWrong
      var somethingWentWrong: RswiftResources.StringResource { .init(key: "somethingWentWrong", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 7 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `primary_color`.
    var primary_color: RswiftResources.ColorResource { .init(name: "primary_color", path: [], bundle: bundle) }

    /// Color `rw-dark`.
    var rwDark: RswiftResources.ColorResource { .init(name: "rw-dark", path: [], bundle: bundle) }

    /// Color `rw-green`.
    var rwGreen: RswiftResources.ColorResource { .init(name: "rw-green", path: [], bundle: bundle) }

    /// Color `rw-light`.
    var rwLight: RswiftResources.ColorResource { .init(name: "rw-light", path: [], bundle: bundle) }

    /// Color `text_foreground`.
    var text_foreground: RswiftResources.ColorResource { .init(name: "text_foreground", path: [], bundle: bundle) }

    /// Color `warning`.
    var warning: RswiftResources.ColorResource { .init(name: "warning", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 68 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `Flag`.
    var flag: RswiftResources.ImageResource { .init(name: "Flag", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Map`.
    var map: RswiftResources.ImageResource { .init(name: "Map", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Monument`.
    var monument: RswiftResources.ImageResource { .init(name: "Monument", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Mural`.
    var mural: RswiftResources.ImageResource { .init(name: "Mural", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Plaque`.
    var plaque: RswiftResources.ImageResource { .init(name: "Plaque", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Sculpture`.
    var sculpture: RswiftResources.ImageResource { .init(name: "Sculpture", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `album_cover`.
    var album_cover: RswiftResources.ImageResource { .init(name: "album_cover", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `apple`.
    var apple: RswiftResources.ImageResource { .init(name: "apple", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrow-left`.
    var arrowLeft: RswiftResources.ImageResource { .init(name: "arrow-left", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `back`.
    var back: RswiftResources.ImageResource { .init(name: "back", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bg_image_mobile`.
    var bg_image_mobile: RswiftResources.ImageResource { .init(name: "bg_image_mobile", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bg_image_tab`.
    var bg_image_tab: RswiftResources.ImageResource { .init(name: "bg_image_tab", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `btn_add`.
    var btn_add: RswiftResources.ImageResource { .init(name: "btn_add", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `calendar_rounded`.
    var calendar_rounded: RswiftResources.ImageResource { .init(name: "calendar_rounded", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `clock`.
    var clock: RswiftResources.ImageResource { .init(name: "clock", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cloud_small`.
    var cloud_small: RswiftResources.ImageResource { .init(name: "cloud_small", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `community`.
    var community: RswiftResources.ImageResource { .init(name: "community", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `copy`.
    var copy: RswiftResources.ImageResource { .init(name: "copy", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `count_background`.
    var count_background: RswiftResources.ImageResource { .init(name: "count_background", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `elephant`.
    var elephant: RswiftResources.ImageResource { .init(name: "elephant", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `facebook_circle`.
    var facebook_circle: RswiftResources.ImageResource { .init(name: "facebook_circle", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `facebook_filled_square`.
    var facebook_filled_square: RswiftResources.ImageResource { .init(name: "facebook_filled_square", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `four_squares`.
    var four_squares: RswiftResources.ImageResource { .init(name: "four_squares", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `frog`.
    var frog: RswiftResources.ImageResource { .init(name: "frog", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `google`.
    var google: RswiftResources.ImageResource { .init(name: "google", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `google-icon`.
    var googleIcon: RswiftResources.ImageResource { .init(name: "google-icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `google-play`.
    var googlePlay: RswiftResources.ImageResource { .init(name: "google-play", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `highlight_1`.
    var highlight_1: RswiftResources.ImageResource { .init(name: "highlight_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `highlight_2`.
    var highlight_2: RswiftResources.ImageResource { .init(name: "highlight_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `highlight_3`.
    var highlight_3: RswiftResources.ImageResource { .init(name: "highlight_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ig_back`.
    var ig_back: RswiftResources.ImageResource { .init(name: "ig_back", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ig_mention`.
    var ig_mention: RswiftResources.ImageResource { .init(name: "ig_mention", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ig_menu`.
    var ig_menu: RswiftResources.ImageResource { .init(name: "ig_menu", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ig_notification`.
    var ig_notification: RswiftResources.ImageResource { .init(name: "ig_notification", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ig_photos`.
    var ig_photos: RswiftResources.ImageResource { .init(name: "ig_photos", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ig_reels`.
    var ig_reels: RswiftResources.ImageResource { .init(name: "ig_reels", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `illustration`.
    var illustration: RswiftResources.ImageResource { .init(name: "illustration", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `imessage`.
    var imessage: RswiftResources.ImageResource { .init(name: "imessage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `landscape_test_image`.
    var landscape_test_image: RswiftResources.ImageResource { .init(name: "landscape_test_image", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `like`.
    var like: RswiftResources.ImageResource { .init(name: "like", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `location`.
    var location: RswiftResources.ImageResource { .init(name: "location", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `logo`.
    var logo: RswiftResources.ImageResource { .init(name: "logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `logo_ford`.
    var logo_ford: RswiftResources.ImageResource { .init(name: "logo_ford", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `monkey`.
    var monkey: RswiftResources.ImageResource { .init(name: "monkey", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `next`.
    var next: RswiftResources.ImageResource { .init(name: "next", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pause`.
    var pause: RswiftResources.ImageResource { .init(name: "pause", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `payment`.
    var payment: RswiftResources.ImageResource { .init(name: "payment", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `play`.
    var play: RswiftResources.ImageResource { .init(name: "play", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `previous`.
    var previous: RswiftResources.ImageResource { .init(name: "previous", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `profile_img`.
    var profile_img: RswiftResources.ImageResource { .init(name: "profile_img", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pumba`.
    var pumba: RswiftResources.ImageResource { .init(name: "pumba", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `queue`.
    var queue: RswiftResources.ImageResource { .init(name: "queue", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `share`.
    var share: RswiftResources.ImageResource { .init(name: "share", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `share_rectangle`.
    var share_rectangle: RswiftResources.ImageResource { .init(name: "share_rectangle", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sleep`.
    var sleep: RswiftResources.ImageResource { .init(name: "sleep", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `speakers`.
    var speakers: RswiftResources.ImageResource { .init(name: "speakers", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `upload_1`.
    var upload_1: RswiftResources.ImageResource { .init(name: "upload_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `upload_2`.
    var upload_2: RswiftResources.ImageResource { .init(name: "upload_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `upload_3`.
    var upload_3: RswiftResources.ImageResource { .init(name: "upload_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `upload_4`.
    var upload_4: RswiftResources.ImageResource { .init(name: "upload_4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `user`.
    var user: RswiftResources.ImageResource { .init(name: "user", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `user_1`.
    var user_1: RswiftResources.ImageResource { .init(name: "user_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `user_2`.
    var user_2: RswiftResources.ImageResource { .init(name: "user_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `user_3`.
    var user_3: RswiftResources.ImageResource { .init(name: "user_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `user_4`.
    var user_4: RswiftResources.ImageResource { .init(name: "user_4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `user_5`.
    var user_5: RswiftResources.ImageResource { .init(name: "user_5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `withdraw`.
    var withdraw: RswiftResources.ImageResource { .init(name: "withdraw", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `withdraw@64`.
    var withdraw64: RswiftResources.ImageResource { .init(name: "withdraw@64", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.file` struct is generated, and contains static references to 2 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `MoviesJson.json`.
    var moviesJsonJson: RswiftResources.FileResource { .init(name: "MoviesJson", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `PublicArt.geojson`.
    var publicArtGeojson: RswiftResources.FileResource { .init(name: "PublicArt", pathExtension: "geojson", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.segue` struct is generated, and contains static references to 1 view controllers.
  struct segue {
    let navigationVC = navigationVC()

    /// This struct is generated for `NavigationVC`, and contains static references to 1 segues.
    struct navigationVC {

      /// Segue identifier `gotoSecondVC`.
      var gotoSecondVC: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, NavigationVC, SecondVC> { .init(identifier: "gotoSecondVC") }
    }
  }

  /// This `_R.id` struct is generated, and contains static references to 1 accessibility identifiers.
  struct id {
    let stackItems = stackItems()

    /// This `_R.id.stackItems` struct is generated, and contains static references to 1 accessibility identifiers.
    struct stackItems {

      /// Accessibility identifier `StackItems`.
      let stackItems = "StackItems"
    }
  }

  /// This `_R.nib` struct is generated, and contains static references to 15 nibs.
  struct nib {
    let bundle: Foundation.Bundle

    /// Nib `CompanyTableViewCell`.
    var companyTableViewCell: RswiftResources.NibReferenceReuseIdentifier<CompanyTableViewCell, CompanyTableViewCell> { .init(name: "CompanyTableViewCell", bundle: bundle, identifier: "CompanyTableViewCell") }

    /// Nib `ContentCollectionViewCell`.
    var contentCollectionViewCell: RswiftResources.NibReferenceReuseIdentifier<ContentCollectionViewCell, ContentCollectionViewCell> { .init(name: "ContentCollectionViewCell", bundle: bundle, identifier: "ContentCollectionViewCell") }

    /// Nib `ContentTableViewCell`.
    var contentTableViewCell: RswiftResources.NibReferenceReuseIdentifier<ContentTableViewCell, ContentTableViewCell> { .init(name: "ContentTableViewCell", bundle: bundle, identifier: "ContentTableViewCell") }

    /// Nib `CustomCallout`.
    var customCallout: RswiftResources.NibReference<CustomCallout> { .init(name: "CustomCallout", bundle: bundle) }

    /// Nib `CustomSectionHeaderView`.
    var customSectionHeaderView: RswiftResources.NibReference<CustomSectionHeaderView> { .init(name: "CustomSectionHeaderView", bundle: bundle) }

    /// Nib `EvenTableViewCell`.
    var evenTableViewCell: RswiftResources.NibReferenceReuseIdentifier<EvenTableViewCell, EvenTableViewCell> { .init(name: "EvenTableViewCell", bundle: bundle, identifier: "EvenTableViewCell") }

    /// Nib `HeaderCollectionViewCell`.
    var headerCollectionViewCell: RswiftResources.NibReferenceReuseIdentifier<HeaderCollectionViewCell, HeaderCollectionViewCell> { .init(name: "HeaderCollectionViewCell", bundle: bundle, identifier: "HeaderCollectionViewCell") }

    /// Nib `HeaderSectionTitle`.
    var headerSectionTitle: RswiftResources.NibReferenceReuseIdentifier<HeaderSectionTitle, HeaderSectionTitle> { .init(name: "HeaderSectionTitle", bundle: bundle, identifier: "HeaderSectionTitle") }

    /// Nib `IndexTableViewCell`.
    var indexTableViewCell: RswiftResources.NibReferenceReuseIdentifier<IndexTableViewCell, IndexTableViewCell> { .init(name: "IndexTableViewCell", bundle: bundle, identifier: "IndexTableViewCell") }

    /// Nib `ProductsTableViewCell`.
    var productsTableViewCell: RswiftResources.NibReferenceReuseIdentifier<ProductsTableViewCell, ProductsTableViewCell> { .init(name: "ProductsTableViewCell", bundle: bundle, identifier: "ProductsTableViewCell") }

    /// Nib `RecommendationCollectionViewCell`.
    var recommendationCollectionViewCell: RswiftResources.NibReferenceReuseIdentifier<RecommendationCollectionViewCell, RecommendationCollectionViewCell> { .init(name: "RecommendationCollectionViewCell", bundle: bundle, identifier: "RecommendationCollectionViewCell") }

    /// Nib `RecommendationTableViewCell`.
    var recommendationTableViewCell: RswiftResources.NibReferenceReuseIdentifier<RecommendationTableViewCell, RecommendationTableViewCell> { .init(name: "RecommendationTableViewCell", bundle: bundle, identifier: "RecommendationTableViewCell") }

    /// Nib `SectionHeader`.
    var sectionHeader: RswiftResources.NibReference<SectionHeader> { .init(name: "SectionHeader", bundle: bundle) }

    /// Nib `StackItems`.
    var stackItems: RswiftResources.NibReference<StackItems> { .init(name: "StackItems", bundle: bundle) }

    /// Nib `UserDataCell`.
    var userDataCell: RswiftResources.NibReferenceReuseIdentifier<UserDataCell, UserDataCell> { .init(name: "UserDataCell", bundle: bundle, identifier: "UserDataCell") }

    func validate() throws {
      if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "playstation.logo") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'playstation.logo' is used in nib 'CompanyTableViewCell', but couldn't be loaded.") } }
      if UIKit.UIImage(named: "kingfisher-10.jpg", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'kingfisher-10.jpg' is used in nib 'ContentCollectionViewCell', but couldn't be loaded.") }
      if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "chevron.right") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'chevron.right' is used in nib 'ContentTableViewCell', but couldn't be loaded.") } }
      if UIKit.UIImage(named: "landscape_test_image", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'landscape_test_image' is used in nib 'HeaderCollectionViewCell', but couldn't be loaded.") }
      if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "star.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'star.fill' is used in nib 'ProductsTableViewCell', but couldn't be loaded.") } }
      if UIKit.UIImage(named: "landscape_test_image", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'landscape_test_image' is used in nib 'RecommendationCollectionViewCell', but couldn't be loaded.") }
      if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "circlebadge") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'circlebadge' is used in nib 'StackItems', but couldn't be loaded.") } }
      if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "person.circle.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'person.circle.fill' is used in nib 'UserDataCell', but couldn't be loaded.") } }
    }
  }

  /// This `_R.reuseIdentifier` struct is generated, and contains static references to 13 reuse identifiers.
  struct reuseIdentifier {

    /// Reuse identifier `CompanyTableViewCell`.
    let companyTableViewCell: RswiftResources.ReuseIdentifier<CompanyTableViewCell> = .init(identifier: "CompanyTableViewCell")

    /// Reuse identifier `ContentCollectionViewCell`.
    let contentCollectionViewCell: RswiftResources.ReuseIdentifier<ContentCollectionViewCell> = .init(identifier: "ContentCollectionViewCell")

    /// Reuse identifier `ContentTableViewCell`.
    let contentTableViewCell: RswiftResources.ReuseIdentifier<ContentTableViewCell> = .init(identifier: "ContentTableViewCell")

    /// Reuse identifier `DemoCollectionViewCell`.
    let demoCollectionViewCell: RswiftResources.ReuseIdentifier<DemoCollectionViewCell> = .init(identifier: "DemoCollectionViewCell")

    /// Reuse identifier `EvenTableViewCell`.
    let evenTableViewCell: RswiftResources.ReuseIdentifier<EvenTableViewCell> = .init(identifier: "EvenTableViewCell")

    /// Reuse identifier `HeaderCollectionViewCell`.
    let headerCollectionViewCell: RswiftResources.ReuseIdentifier<HeaderCollectionViewCell> = .init(identifier: "HeaderCollectionViewCell")

    /// Reuse identifier `HeaderSectionTitle`.
    let headerSectionTitle: RswiftResources.ReuseIdentifier<HeaderSectionTitle> = .init(identifier: "HeaderSectionTitle")

    /// Reuse identifier `IndexTableViewCell`.
    let indexTableViewCell: RswiftResources.ReuseIdentifier<IndexTableViewCell> = .init(identifier: "IndexTableViewCell")

    /// Reuse identifier `ProductsTableViewCell`.
    let productsTableViewCell: RswiftResources.ReuseIdentifier<ProductsTableViewCell> = .init(identifier: "ProductsTableViewCell")

    /// Reuse identifier `RecommendationCollectionViewCell`.
    let recommendationCollectionViewCell: RswiftResources.ReuseIdentifier<RecommendationCollectionViewCell> = .init(identifier: "RecommendationCollectionViewCell")

    /// Reuse identifier `RecommendationTableViewCell`.
    let recommendationTableViewCell: RswiftResources.ReuseIdentifier<RecommendationTableViewCell> = .init(identifier: "RecommendationTableViewCell")

    /// Reuse identifier `TableCell`.
    let tableCell: RswiftResources.ReuseIdentifier<UIKit.UITableViewCell> = .init(identifier: "TableCell")

    /// Reuse identifier `UserDataCell`.
    let userDataCell: RswiftResources.ReuseIdentifier<UserDataCell> = .init(identifier: "UserDataCell")
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 54 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var centerX: centerX { .init(bundle: bundle) }
    var exercise: exercise { .init(bundle: bundle) }
    var instagram: instagram { .init(bundle: bundle) }
    var launchScreen: launchScreen { .init(bundle: bundle) }
    var main: main { .init(bundle: bundle) }
    var multiplier: multiplier { .init(bundle: bundle) }
    var practiceAdvance: practiceAdvance { .init(bundle: bundle) }
    var practiceBasics: practiceBasics { .init(bundle: bundle) }
    var projects: projects { .init(bundle: bundle) }
    var safeArea: safeArea { .init(bundle: bundle) }
    var screenFirstViewController: screenFirstViewController { .init(bundle: bundle) }
    var screenSecondViewController: screenSecondViewController { .init(bundle: bundle) }
    var screenThirdViewController: screenThirdViewController { .init(bundle: bundle) }
    var sizeClass: sizeClass { .init(bundle: bundle) }
    var tilesScene: tilesScene { .init(bundle: bundle) }
    var uiActivityIndicator: uiActivityIndicator { .init(bundle: bundle) }
    var uiAddContacts: uiAddContacts { .init(bundle: bundle) }
    var uiBasicCollectionView: uiBasicCollectionView { .init(bundle: bundle) }
    var uiButton: uiButton { .init(bundle: bundle) }
    var uiCollectionView: uiCollectionView { .init(bundle: bundle) }
    var uiDatePicker: uiDatePicker { .init(bundle: bundle) }
    var uiHomePage: uiHomePage { .init(bundle: bundle) }
    var uiImagePicker: uiImagePicker { .init(bundle: bundle) }
    var uiImageView: uiImageView { .init(bundle: bundle) }
    var uiLabels: uiLabels { .init(bundle: bundle) }
    var uiListContacts: uiListContacts { .init(bundle: bundle) }
    var uiLogin: uiLogin { .init(bundle: bundle) }
    var uiMapView: uiMapView { .init(bundle: bundle) }
    var uiNavigation: uiNavigation { .init(bundle: bundle) }
    var uiOrange: uiOrange { .init(bundle: bundle) }
    var uiPageControl: uiPageControl { .init(bundle: bundle) }
    var uiPageViewController: uiPageViewController { .init(bundle: bundle) }
    var uiPickerView: uiPickerView { .init(bundle: bundle) }
    var uiProductDetails: uiProductDetails { .init(bundle: bundle) }
    var uiProgressView: uiProgressView { .init(bundle: bundle) }
    var uiPullToRefresh: uiPullToRefresh { .init(bundle: bundle) }
    var uiScheduleMeeting: uiScheduleMeeting { .init(bundle: bundle) }
    var uiScrollView: uiScrollView { .init(bundle: bundle) }
    var uiSearchBar: uiSearchBar { .init(bundle: bundle) }
    var uiSegmentedControl: uiSegmentedControl { .init(bundle: bundle) }
    var uiSignUp: uiSignUp { .init(bundle: bundle) }
    var uiSlider: uiSlider { .init(bundle: bundle) }
    var uiStackView: uiStackView { .init(bundle: bundle) }
    var uiStepper: uiStepper { .init(bundle: bundle) }
    var uiStrongReferenceDemo: uiStrongReferenceDemo { .init(bundle: bundle) }
    var uiSwitch: uiSwitch { .init(bundle: bundle) }
    var uiTabBar: uiTabBar { .init(bundle: bundle) }
    var uiTableView: uiTableView { .init(bundle: bundle) }
    var uiTextField: uiTextField { .init(bundle: bundle) }
    var uiTextView: uiTextView { .init(bundle: bundle) }
    var uiToolbar: uiToolbar { .init(bundle: bundle) }
    var uiWebView: uiWebView { .init(bundle: bundle) }
    var uitvAutoResizing: uitvAutoResizing { .init(bundle: bundle) }
    var uiurlSessionBasics: uiurlSessionBasics { .init(bundle: bundle) }

    func centerX(bundle: Foundation.Bundle) -> centerX {
      .init(bundle: bundle)
    }
    func exercise(bundle: Foundation.Bundle) -> exercise {
      .init(bundle: bundle)
    }
    func instagram(bundle: Foundation.Bundle) -> instagram {
      .init(bundle: bundle)
    }
    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func main(bundle: Foundation.Bundle) -> main {
      .init(bundle: bundle)
    }
    func multiplier(bundle: Foundation.Bundle) -> multiplier {
      .init(bundle: bundle)
    }
    func practiceAdvance(bundle: Foundation.Bundle) -> practiceAdvance {
      .init(bundle: bundle)
    }
    func practiceBasics(bundle: Foundation.Bundle) -> practiceBasics {
      .init(bundle: bundle)
    }
    func projects(bundle: Foundation.Bundle) -> projects {
      .init(bundle: bundle)
    }
    func safeArea(bundle: Foundation.Bundle) -> safeArea {
      .init(bundle: bundle)
    }
    func screenFirstViewController(bundle: Foundation.Bundle) -> screenFirstViewController {
      .init(bundle: bundle)
    }
    func screenSecondViewController(bundle: Foundation.Bundle) -> screenSecondViewController {
      .init(bundle: bundle)
    }
    func screenThirdViewController(bundle: Foundation.Bundle) -> screenThirdViewController {
      .init(bundle: bundle)
    }
    func sizeClass(bundle: Foundation.Bundle) -> sizeClass {
      .init(bundle: bundle)
    }
    func tilesScene(bundle: Foundation.Bundle) -> tilesScene {
      .init(bundle: bundle)
    }
    func uiActivityIndicator(bundle: Foundation.Bundle) -> uiActivityIndicator {
      .init(bundle: bundle)
    }
    func uiAddContacts(bundle: Foundation.Bundle) -> uiAddContacts {
      .init(bundle: bundle)
    }
    func uiBasicCollectionView(bundle: Foundation.Bundle) -> uiBasicCollectionView {
      .init(bundle: bundle)
    }
    func uiButton(bundle: Foundation.Bundle) -> uiButton {
      .init(bundle: bundle)
    }
    func uiCollectionView(bundle: Foundation.Bundle) -> uiCollectionView {
      .init(bundle: bundle)
    }
    func uiDatePicker(bundle: Foundation.Bundle) -> uiDatePicker {
      .init(bundle: bundle)
    }
    func uiHomePage(bundle: Foundation.Bundle) -> uiHomePage {
      .init(bundle: bundle)
    }
    func uiImagePicker(bundle: Foundation.Bundle) -> uiImagePicker {
      .init(bundle: bundle)
    }
    func uiImageView(bundle: Foundation.Bundle) -> uiImageView {
      .init(bundle: bundle)
    }
    func uiLabels(bundle: Foundation.Bundle) -> uiLabels {
      .init(bundle: bundle)
    }
    func uiListContacts(bundle: Foundation.Bundle) -> uiListContacts {
      .init(bundle: bundle)
    }
    func uiLogin(bundle: Foundation.Bundle) -> uiLogin {
      .init(bundle: bundle)
    }
    func uiMapView(bundle: Foundation.Bundle) -> uiMapView {
      .init(bundle: bundle)
    }
    func uiNavigation(bundle: Foundation.Bundle) -> uiNavigation {
      .init(bundle: bundle)
    }
    func uiOrange(bundle: Foundation.Bundle) -> uiOrange {
      .init(bundle: bundle)
    }
    func uiPageControl(bundle: Foundation.Bundle) -> uiPageControl {
      .init(bundle: bundle)
    }
    func uiPageViewController(bundle: Foundation.Bundle) -> uiPageViewController {
      .init(bundle: bundle)
    }
    func uiPickerView(bundle: Foundation.Bundle) -> uiPickerView {
      .init(bundle: bundle)
    }
    func uiProductDetails(bundle: Foundation.Bundle) -> uiProductDetails {
      .init(bundle: bundle)
    }
    func uiProgressView(bundle: Foundation.Bundle) -> uiProgressView {
      .init(bundle: bundle)
    }
    func uiPullToRefresh(bundle: Foundation.Bundle) -> uiPullToRefresh {
      .init(bundle: bundle)
    }
    func uiScheduleMeeting(bundle: Foundation.Bundle) -> uiScheduleMeeting {
      .init(bundle: bundle)
    }
    func uiScrollView(bundle: Foundation.Bundle) -> uiScrollView {
      .init(bundle: bundle)
    }
    func uiSearchBar(bundle: Foundation.Bundle) -> uiSearchBar {
      .init(bundle: bundle)
    }
    func uiSegmentedControl(bundle: Foundation.Bundle) -> uiSegmentedControl {
      .init(bundle: bundle)
    }
    func uiSignUp(bundle: Foundation.Bundle) -> uiSignUp {
      .init(bundle: bundle)
    }
    func uiSlider(bundle: Foundation.Bundle) -> uiSlider {
      .init(bundle: bundle)
    }
    func uiStackView(bundle: Foundation.Bundle) -> uiStackView {
      .init(bundle: bundle)
    }
    func uiStepper(bundle: Foundation.Bundle) -> uiStepper {
      .init(bundle: bundle)
    }
    func uiStrongReferenceDemo(bundle: Foundation.Bundle) -> uiStrongReferenceDemo {
      .init(bundle: bundle)
    }
    func uiSwitch(bundle: Foundation.Bundle) -> uiSwitch {
      .init(bundle: bundle)
    }
    func uiTabBar(bundle: Foundation.Bundle) -> uiTabBar {
      .init(bundle: bundle)
    }
    func uiTableView(bundle: Foundation.Bundle) -> uiTableView {
      .init(bundle: bundle)
    }
    func uiTextField(bundle: Foundation.Bundle) -> uiTextField {
      .init(bundle: bundle)
    }
    func uiTextView(bundle: Foundation.Bundle) -> uiTextView {
      .init(bundle: bundle)
    }
    func uiToolbar(bundle: Foundation.Bundle) -> uiToolbar {
      .init(bundle: bundle)
    }
    func uiWebView(bundle: Foundation.Bundle) -> uiWebView {
      .init(bundle: bundle)
    }
    func uitvAutoResizing(bundle: Foundation.Bundle) -> uitvAutoResizing {
      .init(bundle: bundle)
    }
    func uiurlSessionBasics(bundle: Foundation.Bundle) -> uiurlSessionBasics {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.centerX.validate()
      try self.exercise.validate()
      try self.instagram.validate()
      try self.launchScreen.validate()
      try self.main.validate()
      try self.multiplier.validate()
      try self.practiceAdvance.validate()
      try self.practiceBasics.validate()
      try self.projects.validate()
      try self.safeArea.validate()
      try self.screenFirstViewController.validate()
      try self.screenSecondViewController.validate()
      try self.screenThirdViewController.validate()
      try self.sizeClass.validate()
      try self.tilesScene.validate()
      try self.uiActivityIndicator.validate()
      try self.uiAddContacts.validate()
      try self.uiBasicCollectionView.validate()
      try self.uiButton.validate()
      try self.uiCollectionView.validate()
      try self.uiDatePicker.validate()
      try self.uiHomePage.validate()
      try self.uiImagePicker.validate()
      try self.uiImageView.validate()
      try self.uiLabels.validate()
      try self.uiListContacts.validate()
      try self.uiLogin.validate()
      try self.uiMapView.validate()
      try self.uiNavigation.validate()
      try self.uiOrange.validate()
      try self.uiPageControl.validate()
      try self.uiPageViewController.validate()
      try self.uiPickerView.validate()
      try self.uiProductDetails.validate()
      try self.uiProgressView.validate()
      try self.uiPullToRefresh.validate()
      try self.uiScheduleMeeting.validate()
      try self.uiScrollView.validate()
      try self.uiSearchBar.validate()
      try self.uiSegmentedControl.validate()
      try self.uiSignUp.validate()
      try self.uiSlider.validate()
      try self.uiStackView.validate()
      try self.uiStepper.validate()
      try self.uiStrongReferenceDemo.validate()
      try self.uiSwitch.validate()
      try self.uiTabBar.validate()
      try self.uiTableView.validate()
      try self.uiTextField.validate()
      try self.uiTextView.validate()
      try self.uiToolbar.validate()
      try self.uiWebView.validate()
      try self.uitvAutoResizing.validate()
      try self.uiurlSessionBasics.validate()
    }


    /// Storyboard `CenterX`.
    struct centerX: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "CenterX"
      func validate() throws {

      }
    }

    /// Storyboard `Exercise`.
    struct exercise: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = ExerciseVC

      let bundle: Foundation.Bundle

      let name = "Exercise"

      var exerciseVC: RswiftResources.StoryboardViewControllerIdentifier<ExerciseVC> { .init(identifier: "ExerciseVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if UIKit.UIImage(named: "facebook_filled_square", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'facebook_filled_square' is used in storyboard 'Exercise', but couldn't be loaded.") }
        if UIKit.UIImage(named: "google-icon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'google-icon' is used in storyboard 'Exercise', but couldn't be loaded.") }
        if UIKit.UIImage(named: "logo", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'logo' is used in storyboard 'Exercise', but couldn't be loaded.") }
        if exerciseVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'exerciseVC' could not be loaded from storyboard 'Exercise' as 'ExerciseVC'.") }
      }
    }

    /// Storyboard `Instagram`.
    struct instagram: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "Instagram"
      func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "chevron.down.square.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'chevron.down.square.fill' is used in storyboard 'Instagram', but couldn't be loaded.") } }
        if UIKit.UIImage(named: "highlight_1", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'highlight_1' is used in storyboard 'Instagram', but couldn't be loaded.") }
        if UIKit.UIImage(named: "highlight_2", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'highlight_2' is used in storyboard 'Instagram', but couldn't be loaded.") }
        if UIKit.UIImage(named: "highlight_3", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'highlight_3' is used in storyboard 'Instagram', but couldn't be loaded.") }
        if UIKit.UIImage(named: "ig_back", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'ig_back' is used in storyboard 'Instagram', but couldn't be loaded.") }
        if UIKit.UIImage(named: "ig_mention", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'ig_mention' is used in storyboard 'Instagram', but couldn't be loaded.") }
        if UIKit.UIImage(named: "ig_menu", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'ig_menu' is used in storyboard 'Instagram', but couldn't be loaded.") }
        if UIKit.UIImage(named: "ig_notification", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'ig_notification' is used in storyboard 'Instagram', but couldn't be loaded.") }
        if UIKit.UIImage(named: "ig_photos", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'ig_photos' is used in storyboard 'Instagram', but couldn't be loaded.") }
        if UIKit.UIImage(named: "ig_reels", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'ig_reels' is used in storyboard 'Instagram', but couldn't be loaded.") }
        if UIKit.UIImage(named: "profile_img", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'profile_img' is used in storyboard 'Instagram', but couldn't be loaded.") }
        if UIKit.UIImage(named: "upload_1", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'upload_1' is used in storyboard 'Instagram', but couldn't be loaded.") }
        if UIKit.UIImage(named: "upload_2", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'upload_2' is used in storyboard 'Instagram', but couldn't be loaded.") }
        if UIKit.UIImage(named: "upload_3", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'upload_3' is used in storyboard 'Instagram', but couldn't be loaded.") }
        if UIKit.UIImage(named: "upload_4", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'upload_4' is used in storyboard 'Instagram', but couldn't be loaded.") }
      }
    }

    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {

      }
    }

    /// Storyboard `Main`.
    struct main: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UINavigationController

      let bundle: Foundation.Bundle

      let name = "Main"

      var viewController: RswiftResources.StoryboardViewControllerIdentifier<ViewController> { .init(identifier: "ViewController", storyboard: name, bundle: bundle) }

      func validate() throws {
        if viewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'viewController' could not be loaded from storyboard 'Main' as 'ViewController'.") }
      }
    }

    /// Storyboard `Multiplier`.
    struct multiplier: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "Multiplier"
      func validate() throws {

      }
    }

    /// Storyboard `PracticeAdvance`.
    struct practiceAdvance: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "PracticeAdvance"
      func validate() throws {

      }
    }

    /// Storyboard `PracticeBasics`.
    struct practiceBasics: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "PracticeBasics"
      func validate() throws {
        if UIKit.UIImage(named: "facebook_circle", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'facebook_circle' is used in storyboard 'PracticeBasics', but couldn't be loaded.") }
        if UIKit.UIImage(named: "google", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'google' is used in storyboard 'PracticeBasics', but couldn't be loaded.") }
        if UIKit.UIImage(named: "location", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'location' is used in storyboard 'PracticeBasics', but couldn't be loaded.") }
      }
    }

    /// Storyboard `Projects`.
    struct projects: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = SpotifyVC

      let bundle: Foundation.Bundle

      let name = "Projects"

      var pagoVC: RswiftResources.StoryboardViewControllerIdentifier<PagoVC> { .init(identifier: "PagoVC", storyboard: name, bundle: bundle) }
      var shareScreenVC: RswiftResources.StoryboardViewControllerIdentifier<ShareScreenVC> { .init(identifier: "ShareScreenVC", storyboard: name, bundle: bundle) }
      var spotifyVC: RswiftResources.StoryboardViewControllerIdentifier<SpotifyVC> { .init(identifier: "SpotifyVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if UIKit.UIImage(named: "album_cover", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'album_cover' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "apple", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'apple' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "back", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'back' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "bg_image_mobile", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'bg_image_mobile' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "bg_image_tab", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'bg_image_tab' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "community", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'community' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "copy", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'copy' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "elephant", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'elephant' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "four_squares", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'four_squares' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "frog", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'frog' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "google-play", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'google-play' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "illustration", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'illustration' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "imessage", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'imessage' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "like", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'like' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "monkey", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'monkey' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "next", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'next' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "pause", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'pause' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "payment", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'payment' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "previous", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'previous' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "pumba", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'pumba' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "queue", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'queue' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "share", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'share' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "share_rectangle", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'share_rectangle' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "speakers", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'speakers' is used in storyboard 'Projects', but couldn't be loaded.") }
        if UIKit.UIImage(named: "withdraw", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'withdraw' is used in storyboard 'Projects', but couldn't be loaded.") }
        if pagoVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'pagoVC' could not be loaded from storyboard 'Projects' as 'PagoVC'.") }
        if shareScreenVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'shareScreenVC' could not be loaded from storyboard 'Projects' as 'ShareScreenVC'.") }
        if spotifyVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'spotifyVC' could not be loaded from storyboard 'Projects' as 'SpotifyVC'.") }
      }
    }

    /// Storyboard `SafeArea`.
    struct safeArea: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "SafeArea"
      func validate() throws {

      }
    }

    /// Storyboard `ScreenFirstViewController`.
    struct screenFirstViewController: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "ScreenFirstViewController"

      var screenFirstViewController: RswiftResources.StoryboardViewControllerIdentifier<ScreenFirstViewController> { .init(identifier: "ScreenFirstViewController", storyboard: name, bundle: bundle) }

      func validate() throws {
        if screenFirstViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'screenFirstViewController' could not be loaded from storyboard 'ScreenFirstViewController' as 'ScreenFirstViewController'.") }
      }
    }

    /// Storyboard `ScreenSecondViewController`.
    struct screenSecondViewController: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "ScreenSecondViewController"

      var screenSecondViewController: RswiftResources.StoryboardViewControllerIdentifier<ScreenSecondViewController> { .init(identifier: "ScreenSecondViewController", storyboard: name, bundle: bundle) }

      func validate() throws {
        if screenSecondViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'screenSecondViewController' could not be loaded from storyboard 'ScreenSecondViewController' as 'ScreenSecondViewController'.") }
      }
    }

    /// Storyboard `ScreenThirdViewController`.
    struct screenThirdViewController: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "ScreenThirdViewController"

      var screenThirdViewController: RswiftResources.StoryboardViewControllerIdentifier<ScreenThirdViewController> { .init(identifier: "ScreenThirdViewController", storyboard: name, bundle: bundle) }

      func validate() throws {
        if screenThirdViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'screenThirdViewController' could not be loaded from storyboard 'ScreenThirdViewController' as 'ScreenThirdViewController'.") }
      }
    }

    /// Storyboard `SizeClass`.
    struct sizeClass: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "SizeClass"
      func validate() throws {
        if UIKit.UIImage(named: "album_cover", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'album_cover' is used in storyboard 'SizeClass', but couldn't be loaded.") }
        if UIKit.UIImage(named: "cloud_small", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'cloud_small' is used in storyboard 'SizeClass', but couldn't be loaded.") }
        if UIKit.UIImage(named: "like", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'like' is used in storyboard 'SizeClass', but couldn't be loaded.") }
        if UIKit.UIImage(named: "next", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'next' is used in storyboard 'SizeClass', but couldn't be loaded.") }
        if UIKit.UIImage(named: "pause", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'pause' is used in storyboard 'SizeClass', but couldn't be loaded.") }
        if UIKit.UIImage(named: "previous", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'previous' is used in storyboard 'SizeClass', but couldn't be loaded.") }
        if UIKit.UIImage(named: "queue", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'queue' is used in storyboard 'SizeClass', but couldn't be loaded.") }
        if UIKit.UIImage(named: "share", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'share' is used in storyboard 'SizeClass', but couldn't be loaded.") }
        if UIKit.UIImage(named: "sleep", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'sleep' is used in storyboard 'SizeClass', but couldn't be loaded.") }
        if UIKit.UIImage(named: "speakers", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'speakers' is used in storyboard 'SizeClass', but couldn't be loaded.") }
      }
    }

    /// Storyboard `TilesScene`.
    struct tilesScene: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "TilesScene"
      func validate() throws {
        if UIKit.UIImage(named: "elephant", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'elephant' is used in storyboard 'TilesScene', but couldn't be loaded.") }
        if UIKit.UIImage(named: "frog", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'frog' is used in storyboard 'TilesScene', but couldn't be loaded.") }
        if UIKit.UIImage(named: "monkey", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'monkey' is used in storyboard 'TilesScene', but couldn't be loaded.") }
        if UIKit.UIImage(named: "pumba", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'pumba' is used in storyboard 'TilesScene', but couldn't be loaded.") }
      }
    }

    /// Storyboard `UIActivityIndicator`.
    struct uiActivityIndicator: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIActivityIndicator"

      var activityIndicatorVC: RswiftResources.StoryboardViewControllerIdentifier<ActivityIndicatorVC> { .init(identifier: "ActivityIndicatorVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if activityIndicatorVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'activityIndicatorVC' could not be loaded from storyboard 'UIActivityIndicator' as 'ActivityIndicatorVC'.") }
      }
    }

    /// Storyboard `UIAddContacts`.
    struct uiAddContacts: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIAddContacts"

      var addContactsVC: RswiftResources.StoryboardViewControllerIdentifier<AddContactsVC> { .init(identifier: "AddContactsVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "camera.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'camera.fill' is used in storyboard 'UIAddContacts', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "person") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'person' is used in storyboard 'UIAddContacts', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "person.crop.circle.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'person.crop.circle.fill' is used in storyboard 'UIAddContacts', but couldn't be loaded.") } }
        if addContactsVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'addContactsVC' could not be loaded from storyboard 'UIAddContacts' as 'AddContactsVC'.") }
      }
    }

    /// Storyboard `UIBasicCollectionView`.
    struct uiBasicCollectionView: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIBasicCollectionView"

      var basicCollectionViewVC: RswiftResources.StoryboardViewControllerIdentifier<BasicCollectionViewVC> { .init(identifier: "BasicCollectionViewVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if basicCollectionViewVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'basicCollectionViewVC' could not be loaded from storyboard 'UIBasicCollectionView' as 'BasicCollectionViewVC'.") }
      }
    }

    /// Storyboard `UIButton`.
    struct uiButton: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIButton"

      var buttonVC: RswiftResources.StoryboardViewControllerIdentifier<ButtonVC> { .init(identifier: "ButtonVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if buttonVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'buttonVC' could not be loaded from storyboard 'UIButton' as 'ButtonVC'.") }
      }
    }

    /// Storyboard `UICollectionView`.
    struct uiCollectionView: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UICollectionView"

      var collectionViewVC: RswiftResources.StoryboardViewControllerIdentifier<CollectionViewVC> { .init(identifier: "CollectionViewVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "shippingbox.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'shippingbox.fill' is used in storyboard 'UICollectionView', but couldn't be loaded.") } }
        if collectionViewVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'collectionViewVC' could not be loaded from storyboard 'UICollectionView' as 'CollectionViewVC'.") }
      }
    }

    /// Storyboard `UIDatePicker`.
    struct uiDatePicker: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIDatePicker"

      var datePickerVC: RswiftResources.StoryboardViewControllerIdentifier<DatePickerVC> { .init(identifier: "DatePickerVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if datePickerVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'datePickerVC' could not be loaded from storyboard 'UIDatePicker' as 'DatePickerVC'.") }
      }
    }

    /// Storyboard `UIHomePage`.
    struct uiHomePage: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIHomePage"

      var homePageVC: RswiftResources.StoryboardViewControllerIdentifier<HomePageVC> { .init(identifier: "HomePageVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if homePageVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'homePageVC' could not be loaded from storyboard 'UIHomePage' as 'HomePageVC'.") }
      }
    }

    /// Storyboard `UIImagePicker`.
    struct uiImagePicker: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIImagePicker"

      var imagePickerVC: RswiftResources.StoryboardViewControllerIdentifier<ImagePickerVC> { .init(identifier: "ImagePickerVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "person.circle.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'person.circle.fill' is used in storyboard 'UIImagePicker', but couldn't be loaded.") } }
        if imagePickerVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'imagePickerVC' could not be loaded from storyboard 'UIImagePicker' as 'ImagePickerVC'.") }
      }
    }

    /// Storyboard `UIImageView`.
    struct uiImageView: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIImageView"

      var imageViewVC: RswiftResources.StoryboardViewControllerIdentifier<ImageViewVC> { .init(identifier: "ImageViewVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if UIKit.UIImage(named: "logo_ford", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'logo_ford' is used in storyboard 'UIImageView', but couldn't be loaded.") }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "speaker.slash.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'speaker.slash.fill' is used in storyboard 'UIImageView', but couldn't be loaded.") } }
        if imageViewVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'imageViewVC' could not be loaded from storyboard 'UIImageView' as 'ImageViewVC'.") }
      }
    }

    /// Storyboard `UILabels`.
    struct uiLabels: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UILabels"

      var labelsVC: RswiftResources.StoryboardViewControllerIdentifier<LabelsVC> { .init(identifier: "LabelsVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if labelsVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'labelsVC' could not be loaded from storyboard 'UILabels' as 'LabelsVC'.") }
      }
    }

    /// Storyboard `UIListContacts`.
    struct uiListContacts: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIListContacts"

      var listContactsVC: RswiftResources.StoryboardViewControllerIdentifier<ListContactsVC> { .init(identifier: "ListContactsVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if listContactsVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'listContactsVC' could not be loaded from storyboard 'UIListContacts' as 'ListContactsVC'.") }
      }
    }

    /// Storyboard `UILogin`.
    struct uiLogin: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UILogin"

      var loginVC: RswiftResources.StoryboardViewControllerIdentifier<LoginVC> { .init(identifier: "LoginVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if loginVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'loginVC' could not be loaded from storyboard 'UILogin' as 'LoginVC'.") }
      }
    }

    /// Storyboard `UIMapView`.
    struct uiMapView: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = MapViewVC

      let bundle: Foundation.Bundle

      let name = "UIMapView"

      var mapViewVC: RswiftResources.StoryboardViewControllerIdentifier<MapViewVC> { .init(identifier: "MapViewVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if mapViewVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'mapViewVC' could not be loaded from storyboard 'UIMapView' as 'MapViewVC'.") }
      }
    }

    /// Storyboard `UINavigation`.
    struct uiNavigation: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UINavigationController

      let bundle: Foundation.Bundle

      let name = "UINavigation"

      var fourthVC: RswiftResources.StoryboardViewControllerIdentifier<FourthVC> { .init(identifier: "FourthVC", storyboard: name, bundle: bundle) }
      var navigationVC: RswiftResources.StoryboardViewControllerIdentifier<NavigationVC> { .init(identifier: "NavigationVC", storyboard: name, bundle: bundle) }
      var secondVC: RswiftResources.StoryboardViewControllerIdentifier<SecondVC> { .init(identifier: "SecondVC", storyboard: name, bundle: bundle) }
      var thirdVC: RswiftResources.StoryboardViewControllerIdentifier<ThirdVC> { .init(identifier: "ThirdVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "square.and.arrow.up.trianglebadge.exclamationmark") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'square.and.arrow.up.trianglebadge.exclamationmark' is used in storyboard 'UINavigation', but couldn't be loaded.") } }
        if fourthVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'fourthVC' could not be loaded from storyboard 'UINavigation' as 'FourthVC'.") }
        if navigationVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'navigationVC' could not be loaded from storyboard 'UINavigation' as 'NavigationVC'.") }
        if secondVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'secondVC' could not be loaded from storyboard 'UINavigation' as 'SecondVC'.") }
        if thirdVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'thirdVC' could not be loaded from storyboard 'UINavigation' as 'ThirdVC'.") }
      }
    }

    /// Storyboard `UIOrange`.
    struct uiOrange: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIOrange"

      var collectionViewProjectVC: RswiftResources.StoryboardViewControllerIdentifier<CollectionViewProjectVC> { .init(identifier: "CollectionViewProjectVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "chevron.left") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'chevron.left' is used in storyboard 'UIOrange', but couldn't be loaded.") } }
        if UIKit.UIImage(named: "user", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'user' is used in storyboard 'UIOrange', but couldn't be loaded.") }
        if collectionViewProjectVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'collectionViewProjectVC' could not be loaded from storyboard 'UIOrange' as 'CollectionViewProjectVC'.") }
      }
    }

    /// Storyboard `UIPageControl`.
    struct uiPageControl: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIPageControl"

      var pageControlVC: RswiftResources.StoryboardViewControllerIdentifier<PageControlVC> { .init(identifier: "PageControlVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if pageControlVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'pageControlVC' could not be loaded from storyboard 'UIPageControl' as 'PageControlVC'.") }
      }
    }

    /// Storyboard `UIPageViewController`.
    struct uiPageViewController: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIPageViewController"

      var pageViewVC: RswiftResources.StoryboardViewControllerIdentifier<PageViewVC> { .init(identifier: "PageViewVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if pageViewVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'pageViewVC' could not be loaded from storyboard 'UIPageViewController' as 'PageViewVC'.") }
      }
    }

    /// Storyboard `UIPickerView`.
    struct uiPickerView: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIPickerView"

      var pickerViewVC: RswiftResources.StoryboardViewControllerIdentifier<PickerViewVC> { .init(identifier: "PickerViewVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if pickerViewVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'pickerViewVC' could not be loaded from storyboard 'UIPickerView' as 'PickerViewVC'.") }
      }
    }

    /// Storyboard `UIProductDetails`.
    struct uiProductDetails: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIProductDetails"

      var productDetailsVC: RswiftResources.StoryboardViewControllerIdentifier<ProductDetailsVC> { .init(identifier: "ProductDetailsVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "person.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'person.fill' is used in storyboard 'UIProductDetails', but couldn't be loaded.") } }
        if productDetailsVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'productDetailsVC' could not be loaded from storyboard 'UIProductDetails' as 'ProductDetailsVC'.") }
      }
    }

    /// Storyboard `UIProgressView`.
    struct uiProgressView: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIProgressView"

      var progressViewVC: RswiftResources.StoryboardViewControllerIdentifier<ProgressViewVC> { .init(identifier: "ProgressViewVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if progressViewVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'progressViewVC' could not be loaded from storyboard 'UIProgressView' as 'ProgressViewVC'.") }
      }
    }

    /// Storyboard `UIPullToRefresh`.
    struct uiPullToRefresh: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIPullToRefresh"

      var pullToRefreshVC: RswiftResources.StoryboardViewControllerIdentifier<PullToRefreshVC> { .init(identifier: "PullToRefreshVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if pullToRefreshVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'pullToRefreshVC' could not be loaded from storyboard 'UIPullToRefresh' as 'PullToRefreshVC'.") }
      }
    }

    /// Storyboard `UIScheduleMeeting`.
    struct uiScheduleMeeting: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = ScheduleMeetingVC

      let bundle: Foundation.Bundle

      let name = "UIScheduleMeeting"

      var scheduleMeetingVC: RswiftResources.StoryboardViewControllerIdentifier<ScheduleMeetingVC> { .init(identifier: "ScheduleMeetingVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if UIKit.UIImage(named: "arrow-left", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'arrow-left' is used in storyboard 'UIScheduleMeeting', but couldn't be loaded.") }
        if UIKit.UIImage(named: "btn_add", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'btn_add' is used in storyboard 'UIScheduleMeeting', but couldn't be loaded.") }
        if UIKit.UIImage(named: "calendar_rounded", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'calendar_rounded' is used in storyboard 'UIScheduleMeeting', but couldn't be loaded.") }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "chevron.down") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'chevron.down' is used in storyboard 'UIScheduleMeeting', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "chevron.forward") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'chevron.forward' is used in storyboard 'UIScheduleMeeting', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "chevron.up") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'chevron.up' is used in storyboard 'UIScheduleMeeting', but couldn't be loaded.") } }
        if UIKit.UIImage(named: "clock", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'clock' is used in storyboard 'UIScheduleMeeting', but couldn't be loaded.") }
        if UIKit.UIColor(named: "primary_color", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'primary_color' is used in storyboard 'UIScheduleMeeting', but couldn't be loaded.") }
        if scheduleMeetingVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'scheduleMeetingVC' could not be loaded from storyboard 'UIScheduleMeeting' as 'ScheduleMeetingVC'.") }
      }
    }

    /// Storyboard `UIScrollView`.
    struct uiScrollView: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIScrollView"

      var scrollViewVC: RswiftResources.StoryboardViewControllerIdentifier<ScrollViewVC> { .init(identifier: "ScrollViewVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if scrollViewVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'scrollViewVC' could not be loaded from storyboard 'UIScrollView' as 'ScrollViewVC'.") }
      }
    }

    /// Storyboard `UISearchBar`.
    struct uiSearchBar: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UISearchBar"

      var searchBarVC: RswiftResources.StoryboardViewControllerIdentifier<SearchBarVC> { .init(identifier: "SearchBarVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if searchBarVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'searchBarVC' could not be loaded from storyboard 'UISearchBar' as 'SearchBarVC'.") }
      }
    }

    /// Storyboard `UISegmentedControl`.
    struct uiSegmentedControl: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UISegmentedControl"

      var segmentedControlVC: RswiftResources.StoryboardViewControllerIdentifier<SegmentedControlVC> { .init(identifier: "SegmentedControlVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if segmentedControlVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'segmentedControlVC' could not be loaded from storyboard 'UISegmentedControl' as 'SegmentedControlVC'.") }
      }
    }

    /// Storyboard `UISignUp`.
    struct uiSignUp: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UISignUp"

      var signUpVC: RswiftResources.StoryboardViewControllerIdentifier<SignUpVC> { .init(identifier: "SignUpVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if signUpVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'signUpVC' could not be loaded from storyboard 'UISignUp' as 'SignUpVC'.") }
      }
    }

    /// Storyboard `UISlider`.
    struct uiSlider: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UISlider"

      var sliderVC: RswiftResources.StoryboardViewControllerIdentifier<SliderVC> { .init(identifier: "SliderVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if sliderVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'sliderVC' could not be loaded from storyboard 'UISlider' as 'SliderVC'.") }
      }
    }

    /// Storyboard `UIStackView`.
    struct uiStackView: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIStackView"

      var stackViewVC: RswiftResources.StoryboardViewControllerIdentifier<StackViewVC> { .init(identifier: "StackViewVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "person.circle.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'person.circle.fill' is used in storyboard 'UIStackView', but couldn't be loaded.") } }
        if stackViewVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'stackViewVC' could not be loaded from storyboard 'UIStackView' as 'StackViewVC'.") }
      }
    }

    /// Storyboard `UIStepper`.
    struct uiStepper: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIStepper"

      var stepperVC: RswiftResources.StoryboardViewControllerIdentifier<StepperVC> { .init(identifier: "StepperVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if stepperVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'stepperVC' could not be loaded from storyboard 'UIStepper' as 'StepperVC'.") }
      }
    }

    /// Storyboard `UIStrongReferenceDemo`.
    struct uiStrongReferenceDemo: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIStrongReferenceDemo"

      var strongReferenceDemoVC: RswiftResources.StoryboardViewControllerIdentifier<StrongReferenceDemoVC> { .init(identifier: "StrongReferenceDemoVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if strongReferenceDemoVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'strongReferenceDemoVC' could not be loaded from storyboard 'UIStrongReferenceDemo' as 'StrongReferenceDemoVC'.") }
      }
    }

    /// Storyboard `UISwitch`.
    struct uiSwitch: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UISwitch"

      var switchVC: RswiftResources.StoryboardViewControllerIdentifier<SwitchVC> { .init(identifier: "SwitchVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if switchVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'switchVC' could not be loaded from storyboard 'UISwitch' as 'SwitchVC'.") }
      }
    }

    /// Storyboard `UITabBar`.
    struct uiTabBar: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UITabBar"

      var homeScreenVC: RswiftResources.StoryboardViewControllerIdentifier<HomeScreenVC> { .init(identifier: "HomeScreenVC", storyboard: name, bundle: bundle) }
      var searchVC: RswiftResources.StoryboardViewControllerIdentifier<SearchVC> { .init(identifier: "SearchVC", storyboard: name, bundle: bundle) }
      var tabBarVC: RswiftResources.StoryboardViewControllerIdentifier<TabBarVC> { .init(identifier: "TabBarVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "house.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'house.fill' is used in storyboard 'UITabBar', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "magnifyingglass") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'magnifyingglass' is used in storyboard 'UITabBar', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "person.circle.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'person.circle.fill' is used in storyboard 'UITabBar', but couldn't be loaded.") } }
        if homeScreenVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'homeScreenVC' could not be loaded from storyboard 'UITabBar' as 'HomeScreenVC'.") }
        if searchVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'searchVC' could not be loaded from storyboard 'UITabBar' as 'SearchVC'.") }
        if tabBarVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'tabBarVC' could not be loaded from storyboard 'UITabBar' as 'TabBarVC'.") }
      }
    }

    /// Storyboard `UITableView`.
    struct uiTableView: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UITableView"

      var tableViewVC: RswiftResources.StoryboardViewControllerIdentifier<TableViewVC> { .init(identifier: "TableViewVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if tableViewVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'tableViewVC' could not be loaded from storyboard 'UITableView' as 'TableViewVC'.") }
      }
    }

    /// Storyboard `UITextField`.
    struct uiTextField: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UITextField"

      var textFieldVC: RswiftResources.StoryboardViewControllerIdentifier<TextFieldVC> { .init(identifier: "TextFieldVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if textFieldVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'textFieldVC' could not be loaded from storyboard 'UITextField' as 'TextFieldVC'.") }
      }
    }

    /// Storyboard `UITextView`.
    struct uiTextView: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UITextView"

      var textViewVC: RswiftResources.StoryboardViewControllerIdentifier<TextViewVC> { .init(identifier: "TextViewVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if textViewVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'textViewVC' could not be loaded from storyboard 'UITextView' as 'TextViewVC'.") }
      }
    }

    /// Storyboard `UIToolbar`.
    struct uiToolbar: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = ToolbarVC

      let bundle: Foundation.Bundle

      let name = "UIToolbar"

      var toolbarVC: RswiftResources.StoryboardViewControllerIdentifier<ToolbarVC> { .init(identifier: "ToolbarVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if toolbarVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'toolbarVC' could not be loaded from storyboard 'UIToolbar' as 'ToolbarVC'.") }
      }
    }

    /// Storyboard `UIWebView`.
    struct uiWebView: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIWebView"

      var webViewVC: RswiftResources.StoryboardViewControllerIdentifier<WebViewVC> { .init(identifier: "WebViewVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if webViewVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'webViewVC' could not be loaded from storyboard 'UIWebView' as 'WebViewVC'.") }
      }
    }

    /// Storyboard `UITVAutoResizing`.
    struct uitvAutoResizing: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UITVAutoResizing"

      var tvAutoResizingVC: RswiftResources.StoryboardViewControllerIdentifier<TVAutoResizingVC> { .init(identifier: "TVAutoResizingVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if tvAutoResizingVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'tvAutoResizingVC' could not be loaded from storyboard 'UITVAutoResizing' as 'TVAutoResizingVC'.") }
      }
    }

    /// Storyboard `UIURLSessionBasics`.
    struct uiurlSessionBasics: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "UIURLSessionBasics"

      var urlSessionBasicsVC: RswiftResources.StoryboardViewControllerIdentifier<URLSessionBasicsVC> { .init(identifier: "URLSessionBasicsVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if urlSessionBasicsVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'urlSessionBasicsVC' could not be loaded from storyboard 'UIURLSessionBasics' as 'URLSessionBasicsVC'.") }
      }
    }
  }
}